### ISSUE TITLE
problem about bam file

### ISSUE THREAD

**Issue by JeremyQuo** [hiruna72/squigualiser#13] opened 2023-04-28 07:42 UTC
What is the out.bam in
squigualiser reform --sig_move_offset 1 --kmer_length 1 -c --bam pass.bam -o test.paf

I run 
guppy_basecaller -i ./single/ -s ./guppy_out -c rna_r9.4.1_70bps_hac.cfg  --device auto --recursive --moves_out --bam_out
samtools merge pass.bam pass/*.bam

Ang uses pass.bam as input and it returns

**_signal move offset value must be smaller than the kmer length._**

Could you give me a workflow that can be applied to guppy?
Many thanks if can help

**Comment by hiruna72** [comment] 2023-04-28 07:59
Hello @JeremyQuo,

Thanks for pointing out this bug in the Read-Me.
It has to be `--sig_move_offset 0` not 1. I just updated it.
Please refer here for the explanation of sig_move_offset (this explanation is correct).

**Comment by JeremyQuo** [comment] 2023-04-30 05:39
It comes with a new error
tag 'ns' is not found. Please check your input SAM/BAM file.

**Comment by hiruna72** [comment] 2023-05-01 00:27
What was the command you used to basecall?

**Comment by hiruna72** [comment] 2023-05-03 00:28
That's strange. What is the guppy version? Can you try with a newer one if you are using an older one? 
The output bam file(s) should have an `ns` tag (number of samples). This can be verified using samtools view.

**Comment by JeremyQuo** [comment] 2023-05-04 05:27
Thanks for your reply.
If I applied the last version(3.8.6) and run the pipeline below,

guppy_basecaller -i ./single/ -s ./guppy_out -c rna_r9.4.1_70bps_hac.cfg --device auto --recursive --moves_out --bam_out &
cd guppy_out
samtools merge pass.bam pass/*.bam
samtools index pass.bam
squigualiser reform --sig_move_offset 0 --kmer_length 1 -c --bam pass.sam -o pass.paf
samtools fastq pass.bam | minimap2 -ax map-ont reference.fa -t 8 --secondary=no -o map_output.sam -
squigualiser realign --bam map_output.sam --paf pass.paf -o realign.bam
And it raise an error

input bam: map_output.sam
input paf: pass.paf
output bam: realign.bam
INFO: supplementary alignments will be skipped.
Error associated paf record is missing for the read id: aef3f737-a454-46c0-824a-8f2a0cfad268
Traceback (most recent call last):
  File "/t1/zhguo/Program/squigualiser/venv3/bin/squigualiser", line 33, in <module>
    sys.exit(load_entry_point('squigualiser==0.0.1', 'console_scripts', 'squigualiser')())
  File "/t1/zhguo/Program/squigualiser/venv3/lib/python3.9/site-packages/squigualiser-0.0.1-py3.9.egg/src/__init__.py", line 30, in main
  File "/t1/zhguo/Program/squigualiser/venv3/lib/python3.9/site-packages/squigualiser-0.0.1-py3.9.egg/src/realign.py", line 41, in run
KeyError: 'aef3f737-a454-46c0-824a-8f2a0cfad268'

Many thanks for your help

**Comment by hiruna72** [comment] 2023-05-04 09:52
Sorry, did you say the guppy version was 6.3.8? because 3.8.6 would be still pretty old. I use 6.3.7 for testing.
About the error, to start with, can you please grep the read_id (aef3f737-a454-46c0-824a-8f2a0cfad268) in pass.paf?

**Comment by JeremyQuo** [comment] 2023-05-06 02:38
sorry it's 6.3.8.
And I check paf file is 0kb file.
when I run 

squigualiser reform --sig_move_offset 0 --kmer_length 1 -c --bam pass.sam -o pass.paf

it returned
kmer_length: 1
sig_move_offset: 0
input bam: pass.bam
output format: paf
output file: pass.paf
Info: Using a stride of 5 for DNA
expected stride of 5 is missing.

**Comment by hasindu2008** [comment] 2023-05-06 03:07
@JeremyQuo 
Would you be able to provide the FAST5 files under `input/` and `reference.fa` if they are not too large? That way @hiruna72 could run on his end and see what is happening.

**Comment by JeremyQuo** [comment] 2023-05-06 03:30
[fast5.tar.gz](https://github.com/hiruna72/squigualiser/files/11411142/fast5.tar.gz)
[reference.zip](https://github.com/hiruna72/squigualiser/files/11411145/reference.zip)
Many thanks for your help.

**Comment by hiruna72** [comment] 2023-05-07 11:30
Hi @JeremyQuo,

I had a look at the commands and dataset provided. 
You have almost got it correct except that you haven't passed `--rna` where necessary. 
Thanks for bringing up this issue. I have updated readme and the code (dev branch) to throw more meaning error messages.

I could generate plots using the following steps. Could you please try again?

```
1. download latest slow5tools binary and extract (https://github.com/hasindu2008/slow5tools/releases/download/v1.0.0/slow5tools-v1.0.0-x86_64-linux-binaries.tar.gz)

2. convert fast5 to slow5
slow5tools f2s fast5 -d slow5 --dump-all true
slow5tools merge slow5 -o reads.blow5

3. reform (provide --rna)
squigualiser reform --sig_move_offset 0 --kmer_length 1 -c --bam pass.sam -o reform.paf --rna

4. plot read to signal alignments (optional)
samtools fasta pass.sam > reads.fasta
squigualiser plot -a reform.paf -s reads.blow5 -f reads.fasta -o reform_plots_dir --rna

5. realign signals using CIGAR string (provide --rna)
squigualiser realign --bam map_output.sam --paf reform.paf -o realign.bam --rna
samtools sort realign.bam -o sorted_realign.bam
samtools index sorted_realign.bam

6. plot reference to signal alignments
squigualiser plot -a sorted_realign.bam -s reads.blow5 -f reference.fa -o realign_plots_dir --rna

```

Here's plot I generated.
[1b90e1f7-cbfd-4d79-a4f7-8f54c1551ff8_.zip](https://github.com/hiruna72/squigualiser/files/11414847/1b90e1f7-cbfd-4d79-a4f7-8f54c1551ff8_.zip)

**Comment by JeremyQuo** [comment] 2023-05-08 07:57
Many thanks

**Comment by JeremyQuo** [comment] 2023-05-09 06:15
when I use
`squigualiser plot_pileup`
it returns
```
plot (RNA 5'->3') region: NC_001547.1:3939-3919	read_id: b86a977d-696d-48c4-86b0-d44023467781
Traceback (most recent call last):
  File "/t1/zhguo/Program/squigualiser/squigualiser/venv3/bin/squigualiser", line 33, in <module>
    sys.exit(load_entry_point('squigualiser==0.0.1', 'console_scripts', 'squigualiser')())
  File "/t1/zhguo/Program/squigualiser/squigualiser/venv3/lib/python3.9/site-packages/squigualiser-0.0.1-py3.9.egg/src/__init__.py", line 30, in main
  File "/t1/zhguo/Program/squigualiser/squigualiser/venv3/lib/python3.9/site-packages/squigualiser-0.0.1-py3.9.egg/src/plot_pileup.py", line 547, in run
  File "/t1/zhguo/Program/squigualiser/squigualiser/venv3/lib/python3.9/site-packages/squigualiser-0.0.1-py3.9.egg/src/plot_pileup.py", line 246, in plot_function_fixed_width
IndexError: list index out of range

```
It seems a problem from one read
Can you add a try and exception to skip the failed read  to generate the final plot

**Comment by JeremyQuo** [comment] 2023-05-09 08:38
Besides, why the plot's region is reversed , especially in your figure(1014-616) rather than 616-1014

**Comment by hiruna72** [comment] 2023-05-09 09:55
Hi @JeremyQuo,

Did you try using the dev branch? If so, you have found a bug :) Can you send the commands to reproduce the error. I suppose this is from the dataset you already shared. I don't think skipping this type of an error is a good thing as it can result in more errors.

In RNA plots, the region is reversed. The signal is not. That is because nanopore RNA reads are sequenced from 3' to 5'. 
Our convention is to always plot the signal in its original orientation. So you will see the polyA tail in the beginning of a RNA plot.

**Comment by JeremyQuo** [comment] 2023-05-11 12:11
Thanks for your help. I tried dev branch and it returns signal HTML file.
My command is as below
`squigualiser plot_pileup -a sorted_realign.bam -s reads.slow5 -f reference.fa -o realign_plots_dir --rna --region NC_001547.1:3919-3939`

**Comment by JeremyQuo** [comment] 2023-05-11 12:12
If I limit the number to 10 and 20, it can return the correct figure.
But it doesn't matter. I gotta what I want
Thank you

**Comment by hiruna72** [comment] 2023-05-11 13:24
Hey, 
I could debug the error. It was a very important bug fix (latest dev branch). 
Thank you very much for finding it! 
I have attached the new pileup plot.
[pileup_.zip](https://github.com/hiruna72/squigualiser/files/11452648/pileup_.zip)

**Comment by hiruna72** [comment] 2023-05-17 23:31
@JeremyQuo 
It is a good question. Can you please open a new issue as this is not related to this one? 
I will close this issue now. Feel free to open again if you face related problems.

**Closed by hiruna72** 2023-05-17 23:31 UTC
